[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
onchain = "J4S8hv9YmzqTsxpv4PWzn4DwMx6o5k3kCAhyQrmRKXcE"

[registry]
url = "https://api.apr.dev"

[provider]
wallet = "~/.config/solana/id.json"
cluster = "Localnet"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
upgradeable = true
