[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_anchor = "2Fr2VCW2fgw7nkfCCBpq67s9J3YCYtmv4TfskJeREAsi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
